### ISSUE TITLE
ng-repeat

### ISSUE THREAD

**Issue by nitishg91** [akreitals/angular-panel-snap#2]
I'm trying to use ng-repeat to change the panel names everytime and it doesn't seem to work!

**Comment by akreitals** [comment]
Could you please provide a little more information, a plunk or jsFiddle would be a great help.

**Comment by Wilzi** [comment]
same problem :(
Here is a JS Bin example: http://jsbin.com/nohemukici/1/edit?html,console,output

I think in akPanelGroup init function should wait until DOM finishes render.
Something like this: http://jsfiddle.net/bruscopelliti/3A7t3/

**Comment by michaelrachlitz** [comment]
+1 - Having the same issue

I am trying to use this as a vertical slider, and the images is dynamic. I wanted to use ng-repeat on images delivered by a angular service.

panel-snap expects the panels to be in place before the service is updated. Is there a way to delay it perhaps?

**Comment by michaelrachlitz** [comment]
shouldnt it be possible to figure out a fix for this using using $timeout inside the directive?

**Comment by michaelrachlitz** [comment]
I have had a look at it.

The reason why ng-repeat inside the panel group does not work, is because the panelgroup is using transclude. Comment out the transclude, replace and template as well as the transcludeFn function inside the directive.

I am not sure what functionality this will ruin, however commenting out these, made my solution work as I intended to. I will look more into the overall performance within a couple of days.

**Comment by akreitals** [comment]
Thanks @Wilzi for the JSBin and @michaelrachlitz for the info above. 

Apologies for the belated response, have been on holiday. But I will look into this immediately and see what we can do.

**Comment by akreitals** [comment]
@michaelrachlitz if I understand you correctly the only functionality that would effect is the panels `activate`, `enter` and `exit` events. These are thrown when a panel is scrolled into or out of, in order to run any methods or animations on a per panel basis.

But this is obviously not ideal and am working on a fix.

**Comment by Wilzi** [comment]
@akreitals Thank you for this quick fix :)
